version: "3.8"

services:
  ase-server:
    image: lroal/ase-server
    hostname: ase-server
    working_dir: /home/sybase
    volumes:
      - sybase-data:/data
    ports:
      - 45000:5000
    tty: true
    entrypoint: "/home/sybase/bin/entrypoint.sh"

volumes:
  sybase-data: