name: Monthly build docker
on:
  schedule:
    - cron: "0 0 1 */2 *"

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        env:
          DOCKER_REPO: larsroald/ase-server
          ASE_URL: ${{ secrets.ASE_URL }}
        run: |
          docker build -t $DOCKER_REPO --build-arg ASE_URL=${ASE_URL} .
          docker push $DOCKER_REPO
